#!/usr/bin/env python3
"""
fgu_analyze_telemetry.py — Analyzes FGU telemetry data for map testing.

Processes CSV log files generated by fgu_telemetry.py to calculate real-world
engine strain metrics (Peak CPU, Sustained Load, VRAM/RAM Spikes).
"""

import csv
import glob
import os
import sys
from datetime import datetime

def find_telemetry_files():
    """Returns a list of all fgu_telemetry_*.csv files sorted by newest first."""
    files = glob.glob("fgu_telemetry_*.csv")
    files.sort(key=os.path.getmtime, reverse=True)
    return files

def prompt_user_for_file(files):
    """Prompts user to select a telemetry file or defaults to the latest one."""
    if not files:
        print("❌ No telemetry CSV files found in this folder.")
        print("Please run fgu_telemetry.py first to generate test data.")
        sys.exit(1)

    latest = files[0]
    print(f"Found {len(files)} telemetry log(s).")
    print(f"Defaulting to newest file: [{latest}]")
    
    choice = input("Press ENTER to analyze this file, or type 'list' to choose another: ").strip().lower()
    
    if choice == 'list':
        print("\nAvailable telemetry logs:")
        for idx, fname in enumerate(files, start=1):
            mtime = datetime.fromtimestamp(os.path.getmtime(fname)).strftime('%Y-%m-%d %H:%M:%S')
            print(f"  [{idx}] {fname:<30} ({mtime})")
        
        try:
            sel = int(input("\nEnter choice number: ")) - 1
            if 0 <= sel < len(files):
                return files[sel]
            else:
                print("Invalid selection. Using default.")
        except ValueError:
            print("Invalid input. Using default.")
            
    return latest

def parse_telemetry(filepath):
    """Parses raw CSV values into metric lists."""
    cpus = []
    rams = []
    timestamps = []
    
    with open(filepath, mode='r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                timestamps.append(row["Timestamp"])
                cpus.append(float(row["CPU_Percent"]))
                rams.append(float(row["RAM_MB"]))
            except (ValueError, KeyError):
                continue
                
    return timestamps, cpus, rams

def analyze_metrics(cpus, rams):
    """Calculates summary metrics from telemetry series."""
    if not cpus:
        return None
        
    sample_count = len(cpus)
    duration_sec = sample_count * 0.5  # 500ms sampling interval
    
    peak_cpu = max(cpus)
    avg_cpu = sum(cpus) / sample_count
    
    # Baseline vs Peak RAM
    baseline_ram = rams[0] if rams else 0.0
    peak_ram = max(rams) if rams else 0.0
    ram_growth = peak_ram - baseline_ram
    
    # Count sustained high CPU load duration (CPU > 70%)
    high_load_samples = sum(1 for c in cpus if c >= 70.0)
    high_load_sec = high_load_samples * 0.5
    
    return {
        "duration_sec": duration_sec,
        "peak_cpu": peak_cpu,
        "avg_cpu": avg_cpu,
        "baseline_ram": baseline_ram,
        "peak_ram": peak_ram,
        "ram_growth": ram_growth,
        "high_load_sec": high_load_sec,
    }

def main():
    print("=" * 60)
    print("         FGU TELEMETRY PERFORMANCE ANALYZER          ")
    print("=" * 60 + "\n")
    
    # 1. Select telemetry log
    files = find_telemetry_files()
    target_file = prompt_user_for_file(files)
    
    # 2. Get map context from user
    print("\n" + "-" * 60)
    map_name = input("📌 Which MAP were you testing during this log? ").strip()
    if not map_name:
        map_name = "Unnamed Test Map"
        
    predicted_score = input("📊 (Optional) Predicted score from fgu_maptest.py [Press Enter to skip]: ").strip()
    
    # 3. Process telemetry data
    timestamps, cpus, rams = parse_telemetry(target_file)
    stats = analyze_metrics(cpus, rams)
    
    if not stats:
        print("❌ Telemetry log contained no valid data points.")
        sys.exit(1)
        
    # 4. Print Summary Report
    print("\n" + "=" * 60)
    print(f"PERFORMANCE SUMMARY: {map_name.upper()}")
    print("=" * 60)
    print(f"Log File Analyzed  : {target_file}")
    print(f"Total Test Duration: {stats['duration_sec']:.1f} seconds")
    if predicted_score:
        print(f"Predicted MPS Score: {predicted_score} pts")
    print("-" * 60)
    
    print("PROCESSOR (CPU STRAIN — LoS & Lighting Math)")
    print(f"  • Peak CPU Usage  : {stats['peak_cpu']:.1f}%")
    print(f"  • Average CPU Load: {stats['avg_cpu']:.1f}%")
    print(f"  • Time spent >70% : {stats['high_load_sec']:.1f} seconds (Hitch/Stutter window)")
    
    print("\nMEMORY (VRAM / RAM FOOTPRINT — Resolution & File Size)")
    print(f"  • Initial RAM     : {stats['baseline_ram']:.1f} MB")
    print(f"  • Peak RAM        : {stats['peak_ram']:.1f} MB")
    print(f"  • Map RAM Growth  : +{stats['ram_growth']:.1f} MB")
    print("-" * 60)

    # Simple verdict calculation
    if stats['peak_cpu'] >= 85.0 or stats['high_load_sec'] >= 3.0:
        verdict = "🔴 HIGH ENGINE STRAIN (Risk of token drag stutter or client freeze)"
    elif stats['peak_cpu'] >= 50.0 or stats['high_load_sec'] > 0:
        verdict = "🟡 MODERATE STRAIN (Playable, minor hitching possible)"
    else:
        verdict = "🟢 SMOOTH PERFORMANCE (Engine handles map easily)"
        
    print(f"VERDICT: {verdict}")
    print("=" * 60 + "\n")

    # 5. Append summary to history log
    history_file = "fgu_benchmarks.csv"
    file_exists = os.path.isfile(history_file)
    
    with open(history_file, mode="a", newline="") as hf:
        writer = csv.writer(hf)
        if not file_exists:
            writer.writerow(["Timestamp", "Map_Name", "Predicted_Score", "Duration_Sec", 
                             "Peak_CPU", "Avg_CPU", "High_Load_Sec", "RAM_Growth_MB", "Log_File"])
        
        writer.writerow([
            datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            map_name,
            predicted_score or "N/A",
            f"{stats['duration_sec']:.1f}",
            f"{stats['peak_cpu']:.1f}",
            f"{stats['avg_cpu']:.1f}",
            f"{stats['high_load_sec']:.1f}",
            f"{stats['ram_growth']:.1f}",
            target_file
        ])
        
    print(f"✅ Summary saved to history database: {history_file}\n")

if __name__ == "__main__":
    main()
